title:            "吕小荣"
description:      "一个程序员"
url:              "http://mednoter.com"
signoff:          "吕小荣"
disqus_shortname: "mednoter"
facebook_appid:   "407484809306168"
google_analytics: ""
timezone:         Asia/Beijing
highlighter:      pygments

links:
  - name:         Blog
    url:          /
  - name:         Friends
    url:          /links.html
  - name:         RSS
    url:          /feed.xml
  - name:         About
    url:          /about.html

permalink:        /:title.html
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
    - tables
    - with_toc_data
    - strikethrough
    - no_intra_emphasis
    - fenced_code_blocks
    - space_after_headers
